# Generated by Django 4.2 on 2024-02-26 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0003_alter_mail_period_alter_mail_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='client',
        ),
        migrations.AddField(
            model_name='mail',
            name='date_next',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='следующая дата рассылки'),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(max_length=50, verbose_name='Статус попытки'),
        ),
    ]
