# Generated by Django 4.2 on 2024-03-09 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0005_client_owner_mail_owner_message_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail',
            options={'permissions': [('set_is_active', 'Активация рассылки')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterField(
            model_name='mail',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активация рассылки'),
        ),
    ]
